#MEGA
TITLE: Nucleotide

#Seq1 ATGGGAGCGGGGGCGTCTGTTTTGAGGGGAGAGAAGCTAGATACATGGGA
#Seq2   ATGGGTGCGAGAGCGTCAGTATTAAGCGGGAAAAAATTAGATTCATGGGA

#Seq1 AAGTATCAGGCTTCGGCCCGGTGGCAAGAAAAAGTACATGATAAAACATC
#Seq2   GAAAATTCGGTTAAGGCCAGGGGGAAACAAAAAATATAGACTGAAACATT

#Seq1 TGGTTTGGGCAAGATCGGAGCTGCAGCGTTTTGCGCTCAGCTCCTCCCTT
#Seq2   TAGTATGGGCAAGCAGGGAGCTGGAAAAATTCACACTTAACCCTGGCCTT

#Seq1 CTAGAAACATCAGAAGGTTGTGAAAAGGCTATCCATCAATTGAGCCCTTC
#Seq2   TTAGAAACAGCAGAAGGATGTCAGCAAATACTGGGACAATTACAACCAGC

#Seq1 CATAGAAATAAGATCCCCTGAAATAATATCTTTGTTTAACACCATTTGTG
#Seq2   TCTCCAGACAGGAACAGAAGAACTTAGATCATTATATAATACAGTAGCAG